backend:
  image:
    repository: "vizards-backend"
    tag: "v1"
  replicaCount: 1
  service:
    port: 80
  env:
    DATABASE_HOST: "vizards-database"
    DATABASE_PORT: "5432"
    DATABASE_NAME: "wudadb"
    DATABASE_USER: "postgres"
    DATABASE_PASSWORD: "change-me"

frontend:
  image:
    repository: "vizards-frontend"
    tag: "v1"
  replicaCount: 2
  service:
    type: NodePort
    port: 8000

database:
  enabled: true
  image:
    repository: "postgres"
    tag: "15.0"
  replicaCount: 1
  env:
    POSTGRES_DB: "wudadb"
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "change-me"

monitoring:
  enabled: true
  otel:
    image: otel/opentelemetry-collector-contrib:latest
  prometheus:
    image: prom/prometheus:latest
  grafana:
    image: grafana/grafana:latest
    adminPassword: "admin"
